return {}

-- return {
--     'nvim-telescope/telescope.nvim', tag = '0.1.3',
--     dependencies = {
--         'nvim-lua/plenary.nvim' ,
--         'nvim-tree/nvim-web-devicons',
--     },
--     opts = {
--     },
--     config = function()
--         local utils = require("telescope.utils")
--         local builtin = require("telescope.builtin")
--         local actions = require("telescope.actions")
--         -- local git_or_local_files = function()
--         --     local _, ret, _ = utils.get_os_command_output({ 'git', 'rev-parse', '--is-inside-work-tree' })
--         --     if ret == 0 then
--         --         builtin.git_files()
--         --     else
--         --         builtin.find_files()
--         --     end
--         -- end
--         vim.keymap.set('n', '<c-p>', builtin.find_files, {})
--         vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
--         vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
--         vim.keymap.set('n', '<leader>fo', builtin.oldfiles, {})
--         vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
--         vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
--         vim.keymap.set('n', '<leader>fd', builtin.diagnostics, {})
--         vim.keymap.set('n', '<leader>fs', builtin.lsp_document_symbols, {})
--         vim.keymap.set('n', '<leader>fS', builtin.lsp_workspace_symbols, {})
--     end,
-- }
